// Copyright 2022 freznel10 (@freznel10)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#define POINTING_MODES_NUM_DEVICES 2
    #ifdef POINTING_DEVICE_DRIVER_PMW3360
        #define PMW33XX_LIFTOFF_DISTANCE 0x03
        #define POINTING_DEVICE_INVERT_X
        #define POINTING_DEVICE_INVERT_X_RIGHT
        #define PMW33XX_CS_PIN GP14
    #endif //POINTING_DEVICE_DRIVER_PMW3360


#ifdef POINTING_DEVICE_DRIVER_CIRQUE_PINNACLE_SPI
    #define CIRQUE_PINNACLE_DIAMETER_MM 40
    #define CIRQUE_PINNACLE_SPI_CS_PIN GP14
    #define POINTING_DEVICE_ROTATION_270
    #define CIRQUE_PINNACLE_TAP_ENABLE
    #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
        // #define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE
        // #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
    #endif //POINTING_DEVICE_DRIVER_CIRQUE_PINNACLE_SPI
// Trackpoint configuration (commented as reference during cirque migration):
// #define PS2_MOUSE_ROTATE 90
// #define PS2_PIO_USE_PIO1
// #define PS2_MOUSE_X_MULTIPLIER 2
// #define PS2_MOUSE_Y_MULTIPLIER 2
// #define PS2_MOUSE_ENABLE_SCROLLING
// #define PS2_MOUSE_INIT_DELAY 1000
// #define PS2_MOUSE_USE_REMOTE_MODE
