// Copyright 2022 freznel10 (@freznel10)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define POINTING_MODES_NUM_DEVICES 2

#ifdef POINTING_DEVICE_DRIVER_CIRQUE_PINNACLE_SPI
    #define CIRQUE_PINNACLE_DIAMETER_MM 40
    #define CIRQUE_PINNACLE_SPI_CS_PIN GP14
    #define POINTING_DEVICE_ROTATION_270
    #define CIRQUE_PINNACLE_TAP_ENABLE
    #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
        // #define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE
        // #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
    #endif //POINTING_DEVICE_DRIVER_CIRQUE_PINNACLE_SPI
